### ISSUE TITLE
CordovaIsAvailableJob fails on Windows 8, Eclipse Neon

### ISSUE THREAD

**Issue by Selaron** [eclipse/thym#95]
When trying to create a new Hybrid Mobile project, the whizard fails to recognice cordovals version:
```

> 
> java.lang.IllegalArgumentException: invalid version "Microsoft Windows [Version 6.3.9600]
> (c) 2013 Microsoft Corporation. Alle Rechte vorbehalten.
> 
> D:\Programme\eclipse_Neon>cordova -version
> 7.0.1
> 
> D:\Programme\eclipse_Neon>exit": non-numeric "Microsoft Windows [Version 6"
> 	at org.osgi.framework.Version.parseInt(Version.java:170)
> 	at org.osgi.framework.Version.<init>(Version.java:126)
> 	at org.osgi.framework.Version.valueOf(Version.java:257)
> 	at org.osgi.framework.Version.parseVersion(Version.java:228)
> 	at org.eclipse.thym.ui.wizard.project.WizardNewHybridProjectCreationPage$CordovaIsAvailableJob.run(WizardNewHybridProjectCreationPage.java:232)
> 	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
> Caused by: java.lang.NumberFormatException: For input string: "Microsoft Windows [Version 6"
> 	at java.lang.NumberFormatException.forInputString(Unknown Source)
> 	at java.lang.Integer.parseInt(Unknown Source)
> 	at java.lang.Integer.parseInt(Unknown Source)
> 	at org.osgi.framework.Version.parseInt(Version.java:168)
> 	... 5 more
> 


Environment:
I'm using latest developer snapshot of thym as this is able to download stuff from behind a proxy.

> 
> eclipse.buildId=4.6.1.M20160907-1200
> java.version=1.8.0_101
> java.vendor=Oracle Corporation
> BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=de_DE
> Framework arguments:  -product org.eclipse.epp.package.jee.product -product org.eclipse.epp.package.jee.product
> Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.jee.product -data file:/D:/Development/Eclipse/Neon/Mobile/ -product org.eclipse.epp.package.jee.product
>

**Comment by rawagner** [comment]
I pushed a quick-fix for this issue. Wizard should not block you anymore if something goes wrong during detection of cordova version. You can try latest nightly build.
I will debug it properly on Windows later.

**Comment by SSiwek** [comment]
Hi
With which version this issue will be fixed? I have updates/snapshot installed 
  Hybrid Mobile Application Development Tools	2.1.0.201706120616	org.eclipse.thym.feature.feature.group	Eclipse.org - Thym
and it does not work.
Is there a way to get around this issue?
I have to start a new project and I am unsure how to do that without the wizzard...

**Comment by rawagner** [comment]
@SSiwek sorry for late response, I was on PTO and Thym Jenkins instance crashed so there was no updated nightly build. 
It is all fixed now and you can update thym from http://download.eclipse.org/thym/snapshots/
